spring:
  devtools:
    restart:
      enabled: false

  datasource:
    url: jdbc:sqlite:///path/to/web-monitor/db.sqlite
    username:
    password:

logging:
  level:
    org.springframework.web: ERROR
    senntyou.webmonitor: ERROR
