spring:
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:sqlite:///Users/senntyou/space/senn/web-monitor/db.sqlite
    username:
    password:

  thymeleaf:
    prefix: classpath:/templates-dev/
